### PR TITLE
Set 10MB limit on /drip

### PR DESCRIPTION
**Pull request by mansilladev**

### CODE REVIEW

**Comment by kevin1024** [comment]
Should we document this limit somewhere?  Maybe in the readme?

**Comment by mansilladev** [comment]
@kevin1024 - good call. Added to readme.

**Comment by sigmavirus24** [comment]
Sorry, could you provide some reasoning behind this? I'm not opposed I just want to make sure I understand the motivation appropriately given there's bug report this apparently closes or description of the pull request in the original comment.

**Comment by mansilladev** [comment]
Large byte size requests time out after just several MB of xfer in most cases. Also, not having a cap could possibly attract DoS or overflow attack.

**Comment by sigmavirus24** [comment]
Thanks @mansilladev! 🍰 Sorry for the delay

**Pull request merged**
