### PR TITLE
Floating point delays

### PR DESCRIPTION
**Pull request by luhkevin**
Hi,

I needed to implement floating point delays for httpbin and thought I would merge it with the main repo.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I haven't reviewed this yet and don't have strong opinions on the feature, but the commit messages are nearly identical. Please squash them into one commit.

**Comment by kennethreitz** [comment]
No need to add a new endpoint for this, this functionality can be added to the existing delay endpoint.

**Comment by luhkevin** [comment]
Really? I get a 404 when going to http://httpbin.org/delay/0.5
Is there some other way to inject floating point delay that I'm not aware of?

**Comment by luhkevin** [comment]
Oh sorry, I misread your comment.
Yeah I think it could be added quite easily by removing the <int> constraint on the delay parameter.

**Comment by sigmavirus24** [comment]
This looks good to me @Runscope/httpbin . I'd just want to merge this manually to squash the 2 earlier commits

**Comment by luhkevin** [comment]
Sure

**Comment by johnsheehan** [comment]
Fine with me.

**Comment by sigmavirus24** [comment]
Merged in 4763d47

**Pull request closed without merging**
