### PR TITLE
Add ability to specify port/host to run on

### PR DESCRIPTION
**Pull request by s-chizhik**
I guess, it would be good, if users will have ability to run `httpbin` on custom port/host.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Let's use argparse instead. I don't think we should try to divine the meaning of extra parameters to the start-up script.

**Comment by sigmavirus24** [comment]
I'm okay with this. I'd like to know if @darrelmiller can chime in on whether or not the defaults here will work with @Runscope/httpbin 's deployment mechanisms.

**Comment by darrelmiller** [comment]
@sigmavirus24 I wish I could tell you, but I'm not at Runscope anymore.  Maybe @mansilladev  can help.

**Comment by sigmavirus24** [comment]
Sorry @darrelmiller. Didn't notice that. Congrats on the new gig!

**Comment by s-chizhik** [comment]
@sigmavirus24 ping? :)

**Comment by sigmavirus24** [comment]
No one from Runscope chimed in so I guess they don't care.

**Pull request merged**
