### PR TITLE
IP check

### PR DESCRIPTION
**Pull request by failedguidedog**
Added an endpoint that helps one validate Origin IP against specified *valid* or *invalid* IP address or network.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
The tests are failing so there's a problem there. Further, I'm not quite certain this makes sense in HTTPbin. Until there's further discussion, I'm strongly :-1:

**Comment by failedguidedog** [comment]
@sigmavirus24 I'm aware of the failing tests :( For some reason, 'py34' tests fail because 'ipaddr' can't be installed (https://travis-ci.org/Runscope/httpbin/jobs/49579278). Strangely, the tests pass locally when they are run together with 'py27' environment.

Regarding if this makes sense in context of HTTPbin: As far as I'm concerned, this is a feature I needed and it made sense to implement it in this context. I'm contributing it back, because maybe somebody else will need it too. Specifically, this is the only way to implement IP checks when using HAProxy.

I'm willing to put in some more time to figure out why tests fail, but beyond that, I'm happy with using my own fork.

**Comment by johnsheehan** [comment]
Appreciate the contribution! I don't think it's something we want to put on httpbin.org, so I don't think we should merge it in.

**Comment by sigmavirus24** [comment]
So I think cases like this would be easier to handle if we had a clear documentation about the scope of the project. We should sit down and figure out what we want httpbin to be moving forward and how we want to maintain it.

**Pull request closed without merging**
