### PR TITLE
Added support for another Digest algorithm, SHA256.

### PR DESCRIPTION
**Pull request by Jaaap**
RFC 7616 specifies other algorithms for Http Digest:
http://tools.ietf.org/html/rfc7616

I've added support for multiple algorithms in the URLs:
Old:
https://httpbin.org/digest-auth/auth/user/passwd
New:
https://httpbin.org/digest-auth/MD5/auth/user/passwd
https://httpbin.org/digest-auth/SHA-256/auth/user/passwd

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I'm all for supporting new algorithms, but breaking HTTPbin for existing users is entirely unacceptable. We need a new way to do this.

**Comment by johnsheehan** [comment]
Yep, open to the functionality but can't break existing URLs. Maybe a URL
param?

**Comment by Jaaap** [comment]
I've committed a fix (82e67ed) which changes the URL's to

/digest-auth/auth/user/passwd/MD5
and also
/digest-auth/auth/user/passwd
still works.


Teun

**Comment by sigmavirus24** [comment]
Thanks @Jaaap!

**Pull request merged**
